version: "3.7"
services:
  demoseb-app:
    image: myphp
    container_name: demoseb-app
    restart: unless-stopped
    working_dir: /usr/share/nginx/html
    volumes:
      - ./:/usr/share/nginx/html

  demoseb-nginx:
    image: nginx:alpine
    container_name: demoseb-nginx
    restart: unless-stopped
    expose:
       - "80"
    volumes:
      - ./:/usr/share/nginx/html
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    environment:
      VIRTUAL_HOST: demoseb.test
      VIRTUAL_PORT: 80
networks:
  default:
    external:
      name: nginx-proxy
