version: "3.7"
services:
  demoseb-app:
    image: php74
    container_name: demoseb-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - demosebapp

  demoseb-db:
    image: mysqllocal
    container_name: demoseb-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "6034:3306"
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
      - ./docker-compose/mysql/data:/var/lib/mysql
    networks:
      - demosebapp

  demoseb-nginx:
    image: nginxalpine:latest
    container_name: demoseb-nginx
    restart: unless-stopped
    expose:
        - "80"
    environment:
      - VIRTUAL_HOST=demoseb.test
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=sdemoseb.test
      - LETSENCRYPT_EMAIL=sebastien@lhaire.org
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - demosebapp
      - demosebproxy

networks:
  demosebapp:
    driver: bridge
  demosebproxy:
    external:
      name: nginx-proxy
