global.jQuery = require('jquery');
var $ = global.jQuery;
var jQuery = global.JQuery;
window.$ = $;
window.jQuery = jQuery;
require('bootstrap');
import './custom.js';
global.moment = require('moment');
require('daterangepicker');
require('../../vendor/seblhaire/tablebuilder/resources/js/tablebuilder.js');
