<?php
return [
  'draggable' => true,
  'hidden' => false,
  'uploadzoneclass' => 'uploadzone',
  'acceptable_mimes' => 'png,jpg,jpeg,gif,txt',
  'droptext' => '#uploader::messages.droptext#',
  'formclass' => '',
  'formstyle' => '',
  'divclass' => 'form-row',
  'divcol' => 'form-group col-md-2',
  'labelclass' => '',
  'buttonclass' => 'btn btn-dark',
  'uploadicon' => "fas fa-upload",
  'uploadtext' => "#uploader::messages.uploadtext#",
  'uploadcompletetext' => "#uploader::messages.uploadcompletetext#",
  'progbarmainclass' => "progress",
  'progressbarwidth' => '40%',
  "progressbar" => "progress-bar progress-bar-striped progress-bar-animated",
  'failmessage' => "#uploader::messages.failmessage#",
  'alerterrorclass' => 'alert alert-danger',
  'alertsuccessclass' => 'alert alert-success',
  'alerttimeout' => 10000,
  'defaultpath' => "/",
  'resultclass' => 'UploadresultProcessor',
  'errorfn' => null,
  'buildresultdivfn' => 'builduploadresultdiv',
  'maxfilesizek' => 1024,
];
