<?php
// generated by ./serversion.php . Don't modify

return [
  "lastmodif" => "Sep 13, 2022",
  "autocompleter" => "1.2.2",
  "bootstrappaginator" => "1.1.3",
  "daterangepickerhelper" => "2.1.9",
  "formsbootstrap" => "1.0.8",
  "menuandtabutils" => "2.0.0",
  "tablebuilder" => "2.0.0",
  "tagsinput" => "3.0.1",
  "uploader" => "3.0.4",
  "fontawesome" => "6.1.1",
  "bootstrap" => "5.2.0",
  "jquery" => "3.6.0",
  "daterangepicker" => "3.1.0",
];
