<?php
// generated by ./serversion.php . Don't modify

return [
  "lastmodif" => "Nov 28, 2022",
  "autocompleter" => "1.2.3",
  "bootstrappaginator" => "1.1.3",
  "daterangepickerhelper" => "2.1.9",
  "formsbootstrap" => "2.1.7",
  "menuandtabutils" => "2.0.0",
  "tablebuilder" => "2.0.2",
  "tagsinput" => "3.1.2",
  "uploader" => "4.1.0",
  "fontawesome" => "6.2.0",
  "bootstrap" => "5.2.2",
  "jquery" => "3.6.1",
  "daterangepicker" => "3.1.0",
];
