<?php
// generated by ./serversion.php . Don't modify

return [
  "lastmodif" => "Jan 29, 2024",
  "autocompleter" => "1.4.0",
  "bootstrappaginator" => "1.2.0",
  "daterangepickerhelper" => "2.4.0",
  "formsbootstrap" => "2.4.0",
  "menuandtabutils" => "2.1.0",
  "tablebuilder" => "2.2.1",
  "tagsinput" => "3.2.1",
  "uploader" => "4.2.1",
  "fontawesome" => "6.5.1",
  "bootstrap" => "5.3.2",
  "jquery" => "3.7.1",
  "daterangepicker" => "3.1.0",
];
